[tool.poetry]
name = "transformers-scripts"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "convert"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
